//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBodyScanner.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraBD
    {
        public int IDEntradaBD { get; set; }
        public string NombreDocBD { get; set; }
        public string FechaBD { get; set; }
        public string HoraBD { get; set; }
        public Nullable<int> IDDorctorBD { get; set; }
        public string EquipoBD { get; set; }
    
        public virtual DoctorBD DoctorBD { get; set; }
    }
}
