//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBodyScanner.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcupacionesBD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OcupacionesBD()
        {
            this.PacientesBD = new HashSet<PacientesBD>();
        }
    
        public int IDOcupBD { get; set; }
        public string NomOcuBD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacientesBD> PacientesBD { get; set; }
    }
}
