//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBodyScanner.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacientesBD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PacientesBD()
        {
            this.ResultadosBD = new HashSet<ResultadosBD>();
        }
    
        public int IDPacienteBD { get; set; }
        public string NombPCBD { get; set; }
        public string APaterBD { get; set; }
        public string AMaterBD { get; set; }
        public string CorreoPCBD { get; set; }
        public string TelPCBD { get; set; }
        public Nullable<int> EdadBD { get; set; }
        public Nullable<int> IDTipoSangre { get; set; }
        public Nullable<int> IDSexo { get; set; }
        public Nullable<int> IDOcupBD { get; set; }
    
        public virtual OcupacionesBD OcupacionesBD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadosBD> ResultadosBD { get; set; }
        public virtual SexoBD SexoBD { get; set; }
        public virtual TipoSangreBD TipoSangreBD { get; set; }
    }
}
