//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBodyScanner.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadosBD
    {
        public int IDResultado { get; set; }
        public Nullable<int> IDPacienteBD { get; set; }
        public string PacienteNom { get; set; }
        public Nullable<int> IDDoctorBD { get; set; }
        public string DoctorNom { get; set; }
        public Nullable<int> IDEnfermedadBD { get; set; }
        public string EnfermedadNom { get; set; }
    
        public virtual DoctorBD DoctorBD { get; set; }
        public virtual EnfermedadesBD EnfermedadesBD { get; set; }
        public virtual PacientesBD PacientesBD { get; set; }
    }
}
